# conda-recipe/meta.yaml
#
# Notes on building the conda package for VACUUMMS from source directory. 
#
# VACUUMMS will build from either the modules on an HPC cluster or 
# from a suitable conda environment, which means using the compiler, etc. 
# in that environment. The latter is used here.
#
# Build the conda package:
#
#   mamba create -n build-env
#   mamba activate build-env
#   mamba install -c conda-forge conda-build
#   cd conda-recipe
#   conda build .
#
# The build environment must include conda-build. Note that when testing install from a local channel, 
# the channel must first be indexed, in order to make the package discoverable, e.g.:
#
#   conda index ~/miniforge3/conda-bld/linux-64/
#   mamba create -n install-env
#   mamba activate install-env
#   mamba install -c local vacuumms
# 
# The package itself is either a tarball vacuumms-<version>-<build_string>.tar.bz2
# or a conda archive vacuumms-<version>-<build_string>.conda depending on which version
# of conda-build is used.
#
# Note the value for source:path below can be replaced with a github address.
#
# Some other things to consider if things don't go smoothly: 
#
#   conda clean --all
#   
# If the build environment or install environment are corrupted, it's best to remove them and start fresh.
# On CARC systems, building script runs best on a compute node. YMMV. 

package:
  name: vacuumms
  version: 1.2.1

source:
  path: ../

build:
  number: 0
  target_platform: linux-64
  script:
    - cmake . -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_CUDA_COMPONENTS=Y -DBUILD_TIFF_UTILS=Y -DBUILD_PYTHON_BINDINGS=Y
    - make -j4 install
    - cp pybind/vacuumms.cpython-313-x86_64-linux-gnu.so $SP_DIR
    - cp libraries/libvacuumms_rt.so $PREFIX/lib/
    - cp libraries/libvacuumms_cpp.so $PREFIX/lib/
    - cp libraries/vacuumms_variational/libvacuumms_variational.so $PREFIX/lib/

  channels:
    - conda-forge

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - python >=3.12
    - cuda
    - xorg-libx11=1.8.7
    - libtiff
    - pybind11
  host:
    - python >=3.12
    - cuda
    - xorg-libx11=1.8.7
    - libtiff
    - pybind11
  run:
    - python >=3.12
    - cuda
    - xorg-libx11=1.8.7
    - libtiff
    - pybind11

  test:
    commands:
      - python -c "import vacuumms; print(vacuumms.__version__)"

about:
  home: https://github.com/VACUUMMS/VACUUMMS
  license: MIT
  license_file: LICENSE.md
  summary: conda package for vacuumms
